name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java: [11, 17, 21]

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'

    - name: Cache Gradle
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Otorgar permisos de ejecución a gradlew
      if: runner.os != 'Windows'
      run: chmod +x gradlew

    - name: Ejecutar tests
      run: ./gradlew test

    - name: Ejecutar build
      run: ./gradlew build

    - name: Generar reporte de cobertura
      run: ./gradlew jacocoTestReport

    - name: Subir cobertura a Codecov
      uses: codecov/codecov-action@v3
      with:
        file: build/reports/jacoco/test/jacocoTestReport.xml
        fail_ci_if_error: false